USE [RXBackend]

CREATE TABLE [dbo].[BAT_IOU](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TO_UPS_ID] [int] NOT NULL,
	[QTY] [decimal](10, 4) NULL,
	[PHARM_TECH] [nchar](10) NOT NULL,
	[SHIP_TECH] [nchar](10) NULL,
	[STATUS] [nchar](3) NULL,
	[CREATED] [datetime] NOT NULL,
	[LAST_USER] [nchar](10) NULL,
	[LAST_UPDATE] [datetime] NULL,
	[CLOSE_DATE] [datetime] NULL,
 CONSTRAINT [PK_BAT_IOU] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[BAT_IOU] ADD  CONSTRAINT [DF_BAT_IOU_CREATED]  DEFAULT (getdate()) FOR [CREATED]
GO

CREATE TABLE [dbo].[STATUS_CODES](
	[CODE] [varchar](3) NOT NULL,
	[CATEGORY] [varchar](30) NOT NULL,
	[DESCRIPTION] [varchar](60) NOT NULL,
 CONSTRAINT [PK_STATUS_CODES] PRIMARY KEY CLUSTERED 
(
	[CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

INSERT INTO STATUS_CODES VALUES('IO', 'IOU', 'Open')
INSERT INTO STATUS_CODES VALUES('IF', 'IOU', 'Filled')
INSERT INTO STATUS_CODES VALUES('IC', 'IOU', 'User Closed')
INSERT INTO STATUS_CODES VALUES('IS', 'IOU', 'System Closed')


CREATE PROC [dbo].[batch_detail_for_completing_iou]
AS
BEGIN
	BEGIN
		SELECT 
			a.ID
			,a.DEL_BAT_ID
			,a.FIL_ID
			,a.FIL_KOP 
			,a.FIL_DATE
			,a.FAC_DCODE + ' - ' + a.FAC_DNAME as FACILITY
			,a.PAT_ID 
			,a.PAT_LNAME + ', ' + a.PAT_FNAME as NAME 
			,a.DRG_DNAME
			,a.DRG_STRENGTH 
			,a.FIL_QTY_DSP as FILL_QTY 
			,i.CREATED as IOU_DATE
			,i.PHARM_TECH as PHARM_TECH 
			,dbo.FAC_HIGHLIGHT_COLOR(a.FAC_DCODE) as COLOR
			,ISNULL(i.[STATUS], 'NA') as [STATUS]
			,ISNULL(QTY, 0) IOU_QTY
		FROM 
			[UPS_Shipping].[dbo].[TO_UPS] a
			LEFT JOIN [CIPS].[dbo].[DEL_BAT] b 
				ON a.DEL_BAT_ID = b.ID
			LEFT JOIN [CIPS].[dbo].[USR] c 
				ON b.PRINT_USR_ID = c.ID
			LEFT JOIN [RXBackend].[dbo].[BAT_COMPLETE] d
				ON d.DEL_BAT_ID=a.DEL_BAT_ID 
			LEFT JOIN [RXBackend].[dbo].[BAT_PRE_PROCESSED] e
				ON a.DEL_BAT_ID=e.DEL_BAT_ID
			LEFT JOIN [RXBackend].[dbo].[BAT_IOU] i
				ON a.ID = i.TO_UPS_ID 
		WHERE 
			i.ID is not null
			and i.STATUS = 'IO'
		ORDER BY
			 a.FIL_KOP
			,NAME;
	END
END


CREATE PROC [dbo].[batch_detail_for_processing_iou]
	@BATCH_ID INT
AS
BEGIN

	BEGIN
		SELECT 
			 a.DEL_BAT_ID
			,a.FAC_DCODE + ' - ' + a.FAC_DNAME as FACILITY
			,a.FAC_DCODE
			,a.ID
			,a.PAT_ID 
			,a.FIL_ID 
			,a.FIL_KOP 
			,a.PAT_LNAME + ', ' + a.PAT_FNAME as NAME 
			,a.DRG_DNAME
			,a.DRG_STRENGTH 
			,a.FIL_QTY_DSP as QTY 
			,a.FAC_NOT_DTEXT as SHIP 
			,c.TCH_INITIALS as TECH 
			,dbo.FAC_HIGHLIGHT_COLOR(a.FAC_DCODE) as COLOR
			,'N' as EXCEPTION
			,ISNULL(i.[STATUS], 'NA') as [STATUS]
			,ISNULL(QTY, 0) IOU_QTY
		FROM 
			[UPS_Shipping].[dbo].[TO_UPS] a
			LEFT JOIN [CIPS].[dbo].[DEL_BAT] b 
				ON a.DEL_BAT_ID = b.ID
			LEFT JOIN [CIPS].[dbo].[USR] c 
				ON b.PRINT_USR_ID = c.ID
			LEFT JOIN [RXBackend].[dbo].[BAT_COMPLETE] d
				ON d.DEL_BAT_ID=a.DEL_BAT_ID 
			LEFT JOIN [RXBackend].[dbo].[BAT_PRE_PROCESSED] e
				ON a.DEL_BAT_ID=e.DEL_BAT_ID
			LEFT JOIN [RXBackend].[dbo].[BAT_IOU] i
				ON a.ID = i.TO_UPS_ID 
		WHERE 
			 a.DEL_BAT_ID = @BATCH_ID
			-- ADDED FOR CIPS 08/2018 UPGRADE
	 		AND a.FIL_QTY_DSP > 0
		ORDER BY
			 a.FIL_KOP
			,NAME;
	END
END

CREATE PROC [dbo].[put_batch_fill_for_iou]
(	@TO_UPS_ID INT,
	@QTY DECIMAL(10,4),
	@TECH NVARCHAR(10)
)
AS

DECLARE @EXISTS BIT;
SET @EXISTS = 0;

SELECT 
	@EXISTS = 1 
FROM 
	BAT_IOU
WHERE 
	[TO_UPS_ID] = @TO_UPS_ID
	AND [CLOSE_DATE] IS NOT NULL

IF (@EXISTS = 0)
	BEGIN 
		INSERT INTO [dbo].[BAT_IOU]
			   ([TO_UPS_ID]
			   ,[QTY]
			   ,[PHARM_TECH]
			   ,[SHIP_TECH]
			   ,[STATUS]
			   ,[CREATED]
			   ,[LAST_USER]
			   ,[LAST_UPDATE]
			   ,[CLOSE_DATE])
		 VALUES
			   (@TO_UPS_ID
			   ,@QTY
			   ,@TECH
			   ,''
			   ,'IO'
			   ,GETDATE()
			   ,''
			   ,NULL
			   ,NULL);
	END
ELSE
	BEGIN
		UPDATE 
			BAT_IOU
		SET
			[QTY] = @QTY
			,[LAST_USER] = @TECH
			,[LAST_UPDATE] = GETDATE()
		WHERE
			[TO_UPS_ID] = @TO_UPS_ID		
	END

CREATE PROC [dbo].[close_iou_request]
(	@TO_UPS_ID INT,
	@TECH NVARCHAR(10),
	@STATUS NVARCHAR(3)
)
AS

UPDATE [dbo].[BAT_IOU]
   SET [SHIP_TECH] = @TECH 
      ,[STATUS] = @STATUS
      ,[LAST_USER] = @TECH
      ,[LAST_UPDATE] = GETDATE()
      ,[CLOSE_DATE] = GETDATE()
 WHERE [TO_UPS_ID] = @TO_UPS_ID


