CREATE PROCEDURE system_close_iou
AS
BEGIN
	SELECT ID
	INTO #iTemp 
	FROM 
	(SELECT ID FROM BAT_IOU 
		WHERE
		 CREATED <=  GETDATE() - 28
		 AND STATUS IN ('IO','IP')

	)as i

	DECLARE @IOU_ID INT

	WHILE (SELECT COUNT(*) FROM #iTemp) > 0
		BEGIN
			SELECT TOP 1 
				@IOU_ID = ID
			FROM #iTemp;

			EXEC [dbo].[close_iou_request] @IOU_ID, 0, 'SYS', 'IS'

			DELETE FROM #iTemp WHERE ID = @IOU_ID;
		END

	IF OBJECT_ID('tempdb..#iTemp') IS NOT NULL DROP TABLE #iTemp

END


EXEC system_close_iou

SELECT * FROM BAT_IOU WHERE CREATED < GETDATE() - 25
AND STATUS IN ('IO','IP')

SELECT * FROM BAT_IOU order by CLOSE_DATE desc
SELECT * FROM BAT_IOU_TRANS order by TRANS_DATE desc

;WITH CTE AS
(
SELECT TOP 5 * FROM BAT_IOU WHERE STATUS IN ('IC')
--UNION
--SELECT TOP 5 * FROM BAT_IOU WHERE STATUS IN ('IF')
)

UPDATE BAT_IOU SET CREATED = GETDATE() - 29, COMP_QTY = 0, STATUS = 'IP'
WHERE ID IN (SELECT ID FROM CTE)


SELECT * FROM STATUS_CODES

SELECT  * FROM BAT_IOU WHERE STATUS IN ('IC', 'IF')
and CREATED < GETDATE() - 27

SELECT  * FROM BAT_IOU WHERE STATUS IN ('IP', 'IO')
and CAST(CREATED as date) = '2020-01-04'
