CREATE proc [dbo].[update_fac_alt_notify]
	@DCODE VARCHAR(8),
	@IOU_EMAIL VARCHAR(4000),
	@MNG VARCHAR(12),
	@IOU_NOTIFY BIT
AS
BEGIN


UPDATE [dbo].[FAC_ALT]
   SET [IOU_EMAIL] = @IOU_EMAIL
      ,[MNG] = @MNG
      ,[IOU_NOTIFY] = @IOU_NOTIFY
 WHERE [DCODE] =@DCODE 

END