CREATE proc [dbo].[update_mng_groups]
	@CODE VARCHAR(12),
	@DESCRIPTION VARCHAR(200),
	@EMAIL VARCHAR(4000),
	@SEND_NOTIFICATION BIT
AS
BEGIN

UPDATE [dbo].[MNG_GROUPS]
   SET [DESCRIPTION] = @DESCRIPTION
      ,[EMAIL] = @EMAIL
      ,[SEND_NOTIFICATION] = @SEND_NOTIFICATION
 WHERE [CODE] = @CODE

END