CREATE PROCEDURE update_ups_table_for_iou
	@UPS_ID INT
AS	
UPDATE [UPS_Shipping].[dbo].[TO_UPS] 
SET PAT_FNAME = c.PAT_FNAME
    ,PAT_LNAME = c.PAT_LNAME 
	,FIL_QTY_DSP = c.FIL_QTY_DSP
	,FIL_PRICE = c.FIL_PRICE
	,DRG_DNAME = c.DRG_DNAME
	,DRG_STRENGTH = c.DRG_STRENGTH
FROM (
	SELECT 
	f.ID as FIL_ID
	,p.FNAME as PAT_FNAME
	,p.LNAME as PAT_LNAME
	,f.QTY_DSP as FIL_QTY_DSP
	,f.PRICE as FIL_PRICE
	,g.DNAME as DRG_DNAME
	,g.STRENGTH as DRG_STRENGTH
	FROM
		[CIPS].[dbo].DEL d
		INNER JOIN [CIPS].[dbo].FIL f
			on d.FIL_ID = f.ID
		INNER JOIN [CIPS].[dbo].FAC c
			on d.FAC_ID = c.ID
		INNER JOIN [CIPS].[dbo].PAT p
			on f.PAT_ID = p.ID
		INNER JOIN [CIPS].[dbo].DRG g
			on f.DRG_ID = g.ID
		LEFT JOIN (SELECT DTEXT, FAC_ID FROM [CIPS].[dbo].FAC_NOT WHERE TITLE = 'SHIPPING') n
			on c.ID = n.FAC_ID	 
	) AS c
WHERE 
    c.FIL_ID = [UPS_Shipping].[dbo].[TO_UPS].FIL_ID
	AND [UPS_Shipping].[dbo].[TO_UPS].ID = @UPS_ID